dist: xenial
services:
  - xvfb
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install qt5-default
install:
  - pip install -r requirements.txt
script: pytest --cov=qplotutils --cov-report html:coverage tests/
